---
crackin:
  name: mystro-client
  scm: git
  changelog: CHANGELOG.md
  branch:
    production: master
    development: develop
  status:
    verbose: true
  version: lib/mystro/client/version.rb
  build:
    command: rake build
    after: []
